// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl6IH6mR8ev8A8Loc62_lcd8izoPTfIPk',
    appId: '1:919570757684:web:2a148e748e88276d133261',
    messagingSenderId: '919570757684',
    projectId: 'noted-7c3bb',
    authDomain: 'noted-7c3bb.firebaseapp.com',
    storageBucket: 'noted-7c3bb.appspot.com',
    measurementId: 'G-9N28FFXFDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP72YZ5GijmoaVyRiJsw-4aoX7FNVnFVY',
    appId: '1:919570757684:android:2e5166c96b81c026133261',
    messagingSenderId: '919570757684',
    projectId: 'noted-7c3bb',
    storageBucket: 'noted-7c3bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYWNPvIRb6Sm_JWZJ1obabaXak8dJV9k',
    appId: '1:919570757684:ios:e254a7a19b090acf133261',
    messagingSenderId: '919570757684',
    projectId: 'noted-7c3bb',
    storageBucket: 'noted-7c3bb.appspot.com',
    iosClientId: '919570757684-8o6vqo7cr26nen1jun995piuo3csh3pu.apps.googleusercontent.com',
    iosBundleId: 'en.limited.noted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYWNPvIRb6Sm_JWZJ1obabaXak8dJV9k',
    appId: '1:919570757684:ios:8d139e0f1ecf6bfc133261',
    messagingSenderId: '919570757684',
    projectId: 'noted-7c3bb',
    storageBucket: 'noted-7c3bb.appspot.com',
    iosClientId: '919570757684-88ctoj01o1pid8o7tgm7nl1m3krtgokf.apps.googleusercontent.com',
    iosBundleId: 'en.limited.noted.RunnerTests',
  );
}
